---
driver_plugin: vagrant
driver_config:
  provider: lxc
  # If I get into polipo for caching...
  http_proxy: http://10.0.3.1:8123
  https_proxy: https://10.0.3.1:8123

platforms:
  - name: ubuntu-1204
    driver_config:
      box: fgrehm/precise64-lxc
      box_url: https://vagrantcloud.com/fgrehm/precise64-lxc

suites:
  - name: default

